// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260121180854_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.RequestManagement.OfferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OfferRequests");
                });

            modelBuilder.Entity("WebApplication3.RequestManagement.OfferRequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfferRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfferRequestId");

                    b.ToTable("OfferRequestHistories");
                });

            modelBuilder.Entity("WebApplication3.Workflows.WorkflowStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowStatuses");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            ActorRole = "salesperson",
                            State = "InProgress",
                            StatusName = "Drafted"
                        },
                        new
                        {
                            Id = 101,
                            ActorRole = "salesperson",
                            State = "Returned",
                            StatusName = "ReturnedByCoordinatorForSalespersonReview"
                        },
                        new
                        {
                            Id = 200,
                            ActorRole = "engineering-coordinator",
                            State = "InProgress",
                            StatusName = "SubmittedBySalesAndPendingEngineeringAssignment"
                        },
                        new
                        {
                            Id = 201,
                            ActorRole = "engineering-coordinator",
                            State = "Returned",
                            StatusName = "ReturnedByEngineerToCoordinatorForReassign"
                        },
                        new
                        {
                            Id = 300,
                            ActorRole = "engineer",
                            State = "InProgress",
                            StatusName = "AssignedToEngineerByCoordinator"
                        },
                        new
                        {
                            Id = 400,
                            ActorRole = "engineer",
                            State = "InProgress",
                            StatusName = "AcceptedAssignmentByEngineer"
                        },
                        new
                        {
                            Id = 500,
                            ActorRole = "engineering-reivewer",
                            State = "InProgress",
                            StatusName = "SubmittedByEngineerForReview"
                        },
                        new
                        {
                            Id = 601,
                            ActorRole = "engineering-reivewer",
                            State = "Returned",
                            StatusName = "ReturnedBySalesToEngineeringReviewer"
                        },
                        new
                        {
                            Id = 600,
                            ActorRole = "salesperson",
                            State = "InProgress",
                            StatusName = "ApprovedByEngineeringReviewer"
                        },
                        new
                        {
                            Id = 700,
                            ActorRole = "salesperson",
                            State = "InProgress",
                            StatusName = "QuotationInProgress"
                        },
                        new
                        {
                            Id = 800,
                            ActorRole = "salesperson",
                            State = "Completed",
                            StatusName = "Awarded"
                        },
                        new
                        {
                            Id = 801,
                            ActorRole = "salesperson",
                            State = "Completed",
                            StatusName = "Lost"
                        });
                });

            modelBuilder.Entity("WebApplication3.Workflows.WorkflowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("WorkflowTransitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "SubmitToEngineering",
                            FromStatusId = 100,
                            ToStatusId = 200
                        },
                        new
                        {
                            Id = 2,
                            Action = "SubmitToEngineering",
                            FromStatusId = 101,
                            ToStatusId = 200
                        },
                        new
                        {
                            Id = 3,
                            Action = "AssignToEngineer",
                            FromStatusId = 200,
                            ToStatusId = 300
                        },
                        new
                        {
                            Id = 4,
                            Action = "ReturnToSales",
                            FromStatusId = 200,
                            ToStatusId = 101
                        },
                        new
                        {
                            Id = 5,
                            Action = "Accept",
                            FromStatusId = 300,
                            ToStatusId = 400
                        },
                        new
                        {
                            Id = 6,
                            Action = "SubmitForReview",
                            FromStatusId = 400,
                            ToStatusId = 500
                        },
                        new
                        {
                            Id = 7,
                            Action = "Approve",
                            FromStatusId = 500,
                            ToStatusId = 600
                        },
                        new
                        {
                            Id = 8,
                            Action = "Accept",
                            FromStatusId = 600,
                            ToStatusId = 700
                        },
                        new
                        {
                            Id = 9,
                            Action = "Awarded",
                            FromStatusId = 700,
                            ToStatusId = 800
                        },
                        new
                        {
                            Id = 10,
                            Action = "Lost",
                            FromStatusId = 700,
                            ToStatusId = 801
                        });
                });

            modelBuilder.Entity("WebApplication3.RequestManagement.OfferRequestHistory", b =>
                {
                    b.HasOne("WebApplication3.RequestManagement.OfferRequest", null)
                        .WithMany("OfferRequestHistories")
                        .HasForeignKey("OfferRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication3.Workflows.WorkflowTransition", b =>
                {
                    b.HasOne("WebApplication3.Workflows.WorkflowStatus", "FromStatus")
                        .WithMany("Transitions")
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Workflows.WorkflowStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WebApplication3.Workflows.TransitionPrecondition", "Precondition", b1 =>
                        {
                            b1.Property<int>("WorkflowTransitionId");

                            b1.Property<bool>("AssignmentRequired");

                            b1.Property<bool>("CommentRequired");

                            b1.Property<bool>("DataRequired");

                            b1.HasKey("WorkflowTransitionId");

                            b1.ToTable("WorkflowTransitions");

                            b1
                                .ToJson("Precondition")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowTransitionId");
                        });

                    b.Navigation("FromStatus");

                    b.Navigation("Precondition");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("WebApplication3.RequestManagement.OfferRequest", b =>
                {
                    b.Navigation("OfferRequestHistories");
                });

            modelBuilder.Entity("WebApplication3.Workflows.WorkflowStatus", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
